# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./

# Install dependencies without running lifecycle scripts, then build
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the TypeScript project
RUN npm run build

# Expose port if needed (not strictly necessary for local MCP over stdio)
# EXPOSE 3000

# Run command - The entrypoint of the MCP server
CMD ["node", "build/index.js"]
